services:
  postgres-test:
    image: postgres:15.2
    container_name: ecommerce-postgres-test
    networks:
      - test-network
    ports:
      - "5433:5432"
    volumes:
      - ecommerce-test-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: ecommerce_test

networks:
  test-network:
    driver: bridge

volumes:
  ecommerce-test-data:
    driver: local
